# Generated by Django 5.2 on 2025-12-16 16:46

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.AddField(
            model_name='report',
            name='reason_five',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason_four',
            field=models.CharField(default=datetime.datetime(2025, 12, 16, 16, 45, 59, 246043, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason_one',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason_three',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason_two',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportMessage',
        ),
    ]
