# Generated by Django 5.2 on 2025-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_report_reason_report_reason_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason_five',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
