# Generated by Django 5.2 on 2025-10-31 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
