# Generated by Django 5.2 on 2025-12-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fifthreason_firstreason_fourthreason_secondreason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason_five',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason_four',
        ),
        migrations.DeleteModel(
            name='FifthReason',
        ),
        migrations.DeleteModel(
            name='FourthReason',
        ),
    ]
