# Generated by Django 5.2 on 2025-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_report_reason_five_remove_report_reason_four_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondReason',
            new_name='ReportMessage',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason_one',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason_three',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reason_two',
            new_name='reason',
        ),
        migrations.DeleteModel(
            name='FirstReason',
        ),
        migrations.DeleteModel(
            name='ThirdReason',
        ),
    ]
