# Generated by Django 5.2 on 2025-10-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_liked_by_post_liked_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_comments',
            new_name='liked_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='liked_posts',
            new_name='liked_by',
        ),
    ]
