# Generated by Django 5.2 on 2025-10-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_liked_comments_comment_liked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follwer',
            new_name='follower',
        ),
    ]
