# Generated by Django 5.2 on 2025-12-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_secondreason_reportmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportmessage'),
        ),
    ]
